# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/cse/Desktop/COMP3601/projects/COMP3601_group/COMP3601_group.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_1/design_1_rst_ps8_0_99M_1.xci
# IP: The module: 'design_1_rst_ps8_0_99M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cse/Desktop/COMP3601/projects/COMP3601_group/COMP3601_group.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_1/design_1_rst_ps8_0_99M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/cse/Desktop/COMP3601/projects/COMP3601_group/COMP3601_group.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_1/design_1_rst_ps8_0_99M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/cse/Desktop/COMP3601/projects/COMP3601_group/COMP3601_group.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_1/design_1_rst_ps8_0_99M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/cse/Desktop/COMP3601/projects/COMP3601_group/COMP3601_group.srcs/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_1/design_1_rst_ps8_0_99M_1.xci
# IP: The module: 'design_1_rst_ps8_0_99M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/cse/Desktop/COMP3601/projects/COMP3601_group/COMP3601_group.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_1/design_1_rst_ps8_0_99M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/cse/Desktop/COMP3601/projects/COMP3601_group/COMP3601_group.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_1/design_1_rst_ps8_0_99M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/cse/Desktop/COMP3601/projects/COMP3601_group/COMP3601_group.gen/sources_1/bd/design_1/ip/design_1_rst_ps8_0_99M_1/design_1_rst_ps8_0_99M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps8_0_99M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
