@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 03 17:51:13 +1100 2023
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim i2s_master_tb_behav -key {Behavioral:sim_1:Functional:i2s_master_tb} -tclbatch i2s_master_tb.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/Mando/Documents/projects/group_project/i2s_master_test_behav.wcfg -log simulate.log"
call xsim  i2s_master_tb_behav -key {Behavioral:sim_1:Functional:i2s_master_tb} -tclbatch i2s_master_tb.tcl -protoinst "protoinst_files/bd_afc3.protoinst" -protoinst "protoinst_files/design_1.protoinst" -view C:/Users/Mando/Documents/projects/group_project/i2s_master_test_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
