@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Oct 04 19:50:31 +1100 2023
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim ws_testbench_behav -key {Behavioral:sim_1:Functional:ws_testbench} -tclbatch ws_testbench.tcl -protoinst "protoinst_files/bd_6f02.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
call xsim  ws_testbench_behav -key {Behavioral:sim_1:Functional:ws_testbench} -tclbatch ws_testbench.tcl -protoinst "protoinst_files/bd_6f02.protoinst" -protoinst "protoinst_files/design_1.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
